require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/MultipleExpectations:
  Max: 10
