title: AI Agents
description: A Ruby SDK for building multi-agent AI workflows
baseurl: ""
url: ""

# Theme
theme: just-the-docs

# Color scheme
color_scheme: ruby

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub
    url: https://github.com/chatwoot/ai-agents

# Footer
footer_content: "Copyright © 2025 Chatwoot Inc."

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
